@startuml
!include https://raw.githubusercontent.com/jasonzou/es-plantuml/master/ES.puml

'Start the event storming digram

title Archival Description Event Storming Diagram - Accession
footer Copyright 2022

HIDE_STEREOTYPE()
LAYOUT_WITH_LEGEND()
BoundedContext(accesion, "test 01"){
Issue(tt0, "Issue Test", "test01" )
Command(tt1, "Command Test", "test01" )
Event(tt2, "Event Test", "test01" )
Aggregate(tt3, "Aggregate Test", "test01" )
}

Actor(j, "Archivist", "Working ata archives")
Rel(j, tt1, "Trigger the command")
Rel(j, tt0, "Trigger the command ")
Rel_D(tt1, tt2, "jdfjklfsda")
Rel_D(tt1, tt2, "jdfjkld fdddsda")

Rel(tt1, tt2)
Rel(tt2, tt3)

note right of j
The card types bounded context is displayed last instead of first.

The card types are displayed in order but not kept on one line.

Also this note is supposed to be at the bottom of the bounded context.
endnote

BoundedContext(accession, "Accession"){
    Group(commandOrder){
    Command(placeOrder, "Create x Order") 
    Command(cancelOrder, "Cancel Order")
    Command(validateOrder, "Validate Order")
    Command(changeOrder, "Change Order")
    Command(saveOrder, "Save Order")
    Command(deleteOrder, "Delete Order")
    }
    Group(eventOrder){
    Event(orderPlaced, "Order Placed") 
    Event(orderCancelled, "Order Cancelled")
    Event(orderValidated, "Order Validated")
    }
}
Actor(j1, "Archivist", "Working at archives")
Rel(j1, placeOrder)
Rel(j1, cancelOrder)
Rel(j1, validateOrder)

Rel(placeOrder, orderPlaced)

Rel(cancelOrder, orderCancelled)

note bottom of tt3
The card types bounded context is displayed last instead of first.

The card types are displayed in order but not kept on one line.

Also this note is supposed to be at the bottom of the bounded context.
endnote
@enduml
